# Screen
WIDTH = 1366
HEIGTH = 700
FPS = 60

# BATTLE UI
HP_BAR_WIDTH = (4 * WIDTH) / 16
BAR_HEIGHT = HP_BAR_WIDTH / 15
UI_FONT = './Assets/fonts/default.ttf'
UI_FONT_SIZE = 18

HP_A_POS_X = (WIDTH * 3) // 100
HP_A_POS_Y = (HEIGTH * 5) // 100
HP_B_POS_X = ((WIDTH * 97) // 100) - HP_BAR_WIDTH
HP_B_POS_Y = ((HEIGTH * 5) // 100)

HPTEXT_A_POS_X = HP_A_POS_X
HPTEXT_A_POS_Y = HP_A_POS_Y - BAR_HEIGHT - 5
HPTEXT_B_POS_X = HP_B_POS_X
HPTEXT_B_POS_Y = HP_B_POS_Y - BAR_HEIGHT - 5

NAMETEXT_A_POS_X = HP_A_POS_X
NAMETEXT_A_POS_Y = HP_A_POS_Y + BAR_HEIGHT + 5
NAMETEXT_B_POS_X = HP_B_POS_X
NAMETEXT_B_POS_Y = HP_B_POS_Y + BAR_HEIGHT + 5

ANCHOR_POINT_X = WIDTH / 2
ANCHOR_POINT_Y = HEIGTH - (HEIGTH / 6)

BUTTON_PADDING = HEIGTH / 18

BUTTON_WIDTH = WIDTH / 8
BUTTON_HEIGTH = HEIGTH / 18

BUTTON_UP_X = ANCHOR_POINT_X
BUTTON_UP_Y = ANCHOR_POINT_Y - BUTTON_PADDING
BUTTON_DOWN_X = ANCHOR_POINT_X
BUTTON_DOWN_Y = ANCHOR_POINT_Y + BUTTON_PADDING
BUTTON_LEFT_X = ANCHOR_POINT_X - BUTTON_PADDING
BUTTON_LEFT_Y = ANCHOR_POINT_Y 
BUTTON_RIGHT_X = ANCHOR_POINT_X + BUTTON_PADDING
BUTTON_RIGHT_Y = ANCHOR_POINT_Y 



# general colors
UI_BG_COLOR = '#2c2c38'
UI_BORDER_COLOR = '#dfdfff'
TEXT_COLOR = "white" # '#000123'

# ui colors
HP_COLOR = '#e00d42'
UI_BORDER_COLOR_ACTIVE = 'black'