# Screen
WIDTH = 1366
HEIGTH = 700
FPS = 60

# BATTLE UI
HP_BAR_WIDTH = (4 * WIDTH) / 16
BAR_HEIGHT = HP_BAR_WIDTH / 15
UI_FONT = './Assets/fonts/default.ttf'
UI_FONT_SIZE = 18

HP_A_POS_X = (WIDTH * 3) // 100
HP_A_POS_Y = (HEIGTH * 5) // 100

HP_B_POS_X = ((WIDTH * 97) // 100) - HP_BAR_WIDTH
HP_B_POS_Y = ((HEIGTH * 5) // 100)

HPTEXT_A_POS_X = HP_A_POS_X
HPTEXT_A_POS_Y = HP_A_POS_Y - BAR_HEIGHT - 5

HPTEXT_B_POS_X = HP_B_POS_X
HPTEXT_B_POS_Y = HP_B_POS_Y - BAR_HEIGHT - 5

NAMETEXT_A_POS_X = HP_A_POS_X
NAMETEXT_A_POS_Y = HP_A_POS_Y + BAR_HEIGHT + 5

NAMETEXT_B_POS_X = HP_B_POS_X
NAMETEXT_B_POS_Y = HP_B_POS_Y + BAR_HEIGHT + 5

# general colors
UI_BG_COLOR = '#2c2c38'
UI_BORDER_COLOR = '#dfdfff'
TEXT_COLOR = "white" # '#000123'

# ui colors
HP_COLOR = '#e00d42'
UI_BORDER_COLOR_ACTIVE = 'black'