# Screen
WIDTH = 1280
HEIGTH = 720
FPS = 60

# Generic
UNIT = HEIGTH // 9
HALF_UNIT = HEIGTH // 18

# Text
UI_FONT = './Assets/fonts/Default.ttf'
UI_FONT_SIZE = HALF_UNIT * 2 // 5
TYPE_FONT_SIZE = HALF_UNIT // 3

# Daos sprites
DAO_A_POS_X = UNIT * 2 + HALF_UNIT
DAO_A_POS_Y = HEIGTH // 2

DAO_B_POS_X = WIDTH - DAO_A_POS_X
DAO_B_POS_Y = HEIGTH // 2

# HP bars
HP_BAR_WIDTH = UNIT * 4
BAR_HEIGHT = HALF_UNIT // 2

HP_A_POS_X = HALF_UNIT
HP_A_POS_Y = HALF_UNIT
HP_B_POS_X = WIDTH - HP_BAR_WIDTH - HALF_UNIT
HP_B_POS_Y = HALF_UNIT

HPTEXT_A_POS_X = HP_A_POS_X
HPTEXT_A_POS_Y = HP_A_POS_Y - BAR_HEIGHT - 5
HPTEXT_B_POS_X = HP_B_POS_X
HPTEXT_B_POS_Y = HP_B_POS_Y - BAR_HEIGHT - 5

NAMETEXT_A_POS_X = HP_A_POS_X
NAMETEXT_A_POS_Y = HP_A_POS_Y + BAR_HEIGHT + 5
NAMETEXT_B_POS_X = HP_B_POS_X
NAMETEXT_B_POS_Y = HP_B_POS_Y + BAR_HEIGHT + 5

INITTEXT_A_POS_X = NAMETEXT_A_POS_X
INITTEXT_A_POS_Y = NAMETEXT_A_POS_Y + BAR_HEIGHT + 5
INITTEXT_B_POS_X = NAMETEXT_B_POS_X
INITTEXT_B_POS_Y = NAMETEXT_B_POS_Y + BAR_HEIGHT + 5

# Type Icon
TYPE_ICON_WIDTH = UNIT
TYPE_ICON_HEIGTH = (HALF_UNIT // 2)

TYPE_ICON1_A_POS_X = HP_A_POS_X + HP_BAR_WIDTH + (HALF_UNIT // 2)
TYPE_ICON1_A_POS_Y = HALF_UNIT
TYPE_ICON1_B_POS_X = HP_B_POS_X - UNIT - (HALF_UNIT // 2)
TYPE_ICON1_B_POS_Y = HALF_UNIT

TYPE_ICON2_A_POS_X = HP_A_POS_X + HP_BAR_WIDTH + UNIT + HALF_UNIT
TYPE_ICON2_A_POS_Y = HALF_UNIT
TYPE_ICON2_B_POS_X = HP_B_POS_X - (2 * UNIT) - HALF_UNIT
TYPE_ICON2_B_POS_Y = HALF_UNIT

TYPE_ICON1_BUTTON_A_POS_X = HP_A_POS_X + HP_BAR_WIDTH + (HALF_UNIT // 2)
TYPE_ICON1_BUTTON_A_POS_Y = HALF_UNIT
TYPE_ICON2_BUTTON_A_POS_X = HP_A_POS_X + HP_BAR_WIDTH + UNIT + HALF_UNIT
TYPE_ICON2_BUTTON_A_POS_Y = HALF_UNIT

TYPE_ICON1_BUTTON_B_POS_X = HP_B_POS_X - UNIT - (HALF_UNIT // 2)
TYPE_ICON1_BUTTON_B_POS_Y = HALF_UNIT
TYPE_ICON2_BUTTON_B_POS_X = HP_B_POS_X - (2 * UNIT) - HALF_UNIT
TYPE_ICON2_BUTTON_B_POS_Y = HALF_UNIT

# Bottom UI anchor points
ANCHOR_POINT_X = WIDTH // 2
ANCHOR_POINT_Y = HALF_UNIT * 14

# Buttons
BUTTON_WIDTH = UNIT * 2
BUTTON_HEIGTH = HALF_UNIT

BUTTON_PADDING_Y = HEIGTH // 16 
BUTTON_PADDING_X = BUTTON_PADDING_Y + (BUTTON_WIDTH // 2)

BUTTON_BANNER_Y_X = ANCHOR_POINT_X - (BUTTON_WIDTH  // 2)
BUTTON_BANNER_Y_Y = ANCHOR_POINT_Y - UNIT - BUTTON_HEIGTH

BUTTON_BANNER_A_X = ANCHOR_POINT_X - (BUTTON_WIDTH  // 2)
BUTTON_BANNER_A_Y = ANCHOR_POINT_Y + UNIT

BUTTON_BANNER_X_X = ANCHOR_POINT_X - UNIT - BUTTON_WIDTH
BUTTON_BANNER_X_Y = ANCHOR_POINT_Y - (BUTTON_HEIGTH  // 2)

BUTTON_BANNER_B_X = ANCHOR_POINT_X + UNIT
BUTTON_BANNER_B_Y = ANCHOR_POINT_Y - (BUTTON_HEIGTH  // 2)

BUTTON_BANNER_L_X = ANCHOR_POINT_X - (2 * UNIT) - BUTTON_WIDTH
BUTTON_BANNER_L_Y = ANCHOR_POINT_Y - UNIT - (HALF_UNIT // 2)

BUTTON_BANNER_R_X = ANCHOR_POINT_X + (2 * UNIT)
BUTTON_BANNER_R_Y = ANCHOR_POINT_Y - UNIT - (HALF_UNIT // 2)

# UI Buttons
BUTTON_ABXY_RADIUS = HALF_UNIT // 2

BUTTON_A_X = ANCHOR_POINT_X - (HALF_UNIT // 2)
BUTTON_A_Y = ANCHOR_POINT_Y + (HALF_UNIT // 2)

BUTTON_B_X = ANCHOR_POINT_X + (HALF_UNIT // 2)
BUTTON_B_Y = ANCHOR_POINT_Y - (HALF_UNIT // 2)

BUTTON_X_X = ANCHOR_POINT_X - HALF_UNIT - (HALF_UNIT // 2)
BUTTON_X_Y = ANCHOR_POINT_Y - (HALF_UNIT // 2)

BUTTON_Y_X = ANCHOR_POINT_X - (HALF_UNIT // 2)
BUTTON_Y_Y = ANCHOR_POINT_Y - HALF_UNIT - (HALF_UNIT // 2)

BUTTON_L_X = ANCHOR_POINT_X - UNIT - HALF_UNIT - (HALF_UNIT // 2)
BUTTON_L_Y = ANCHOR_POINT_Y - UNIT - (HALF_UNIT // 2)

BUTTON_R_X = ANCHOR_POINT_X + UNIT + (HALF_UNIT // 2)
BUTTON_R_Y = ANCHOR_POINT_Y - UNIT - (HALF_UNIT // 2)

# Chatboxes
CHATBOX_WIDTH = WIDTH // 2
CHATBOX_HEIGTH = 2 * UNIT

CHATBOX_POS_X = ANCHOR_POINT_X - (CHATBOX_WIDTH // 2)
CHATBOX_POS_Y = ANCHOR_POINT_Y - (CHATBOX_HEIGTH // 2)

CHATBOX_BUTTON_X = ANCHOR_POINT_X - (HALF_UNIT // 2)
CHATBOX_BUTTON_Y = ANCHOR_POINT_Y + HALF_UNIT + (HALF_UNIT // 2)

# general colors
HP_COLOR = '#e00d42'
HP_SHADOW_COLOR = "#ffb73b"
UI_BG_COLOR = '#2c2c38'
ON_SELECT_COLOR = '#9999c2'
TEXT_COLOR = "white"
RED_TEXT_COLOR = "red"
ABXY_COLOR = "white"